"""
src/validate/check_stage3n_numerical.py

V6 — Stage 3-N (Donut Numerical, fine-tuned) 사후 검증.

★ D-023 사용자 필수 임계값:
- Measure F1   ≥ 0.90 (critical)   ← 논문 0.923
- GDT F1       ≥ 0.95 (critical)   ← 논문 0.965
- Roughness F1 ≥ 0.95 (warning)    ← 논문 1.0
- numerical_accuracy ≥ 0.95 (critical)
- tolerance_match    ≥ 0.90 (critical)
- hallucination_rate < 0.10 (critical)

Inputs
------
- ``--predictions`` : Stage 3-N 출력 폴더 (``*.num.json`` from stage3_numerical.py)
- ``--gt``          : Ground truth 폴더 (``data/vlm/numerical/`` 사람 검수 후)

Predictions format (stage3_numerical.py output)
-----------------------------------------------
::

    {
      "type": "Measure",
      "source": "...",
      "parsed": {
        "nominal": 25.0,
        "tolerance": {"upper": 0.05, "lower": -0.05},
        "unit": "mm"
      },
      "raw_seq": "..."
    }

GT format (training data, after human review)
---------------------------------------------
::

    {
      "type": "Measure",
      "nominal": 25.0,
      "tolerance": {"upper": 0.05, "lower": -0.05},
      "unit": "mm"
    }

Optional ``_review`` block is auto-stripped.

CLI
---
::

    python -m src.validate.check_stage3n_numerical \\
        --predictions outputs/sample/numerical/ \\
        --gt data/vlm/numerical/
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from src.utils.metrics import (
    NUMERICAL_SCHEMAS,
    compare_measure, compare_gdt, compare_roughness,
    hallucination_rate, numerical_match,
    pr_f1, safe_div,
)
from src.validate.common import (
    DEFAULT_REPORTS_DIR, DEFAULT_THRESHOLDS_PATH,
    Severity, Status, ValidationReport,
    load_thresholds, threshold_lookup,
    make_bar_chart, make_confusion_matrix,
    setup_logging,
)

log = setup_logging("validate.stage3n")


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------
def load_json_safe(path: Path) -> Optional[Dict[str, Any]]:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:  # noqa: BLE001
        log.warning("Failed to load %s: %s", path, e)
        return None


def discover_predictions(pred_dir: Path) -> Dict[str, Path]:
    """Return ``{stem: path}`` for ``*.num.json`` and ``*.json`` (excluding manifest)."""
    out: Dict[str, Path] = {}
    for ext in ("*.num.json", "*.json"):
        for p in pred_dir.rglob(ext):
            if p.name in ("manifest.json", "manifest.csv"):
                continue
            stem = p.stem
            if stem.endswith(".num"):
                stem = stem[:-len(".num")]
            if stem not in out:
                out[stem] = p
    return out


def discover_gt(gt_dir: Path) -> Dict[str, Path]:
    """Return ``{stem: path}`` for GT JSONs (only those with completed review)."""
    out: Dict[str, Path] = {}
    for p in gt_dir.rglob("*.json"):
        if p.name in ("manifest.json", "manifest.csv"):
            continue
        out.setdefault(p.stem, p)
    return out


def strip_review(d: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Remove ``_review`` / ``_meta`` blocks from a GT/pred JSON."""
    if not d:
        return {}
    return {k: v for k, v in d.items() if k not in ("_review", "_meta")}


def gt_is_completed(d: Optional[Dict[str, Any]]) -> bool:
    """If GT was generated by prepare_vlm_dataset.py with `_review`, only use
    completed ones. Otherwise (no `_review` block), assume completed."""
    if not d:
        return False
    rev = d.get("_review")
    if rev is None:
        return True
    return bool(rev.get("completed", False))


# ---------------------------------------------------------------------------
# Pair record
# ---------------------------------------------------------------------------
@dataclass
class PairResult:
    image_stem: str
    region_class: str            # "Measure" / "GDT" / "Roughness"
    pred_inner: Dict[str, Any]
    gt_inner: Dict[str, Any]
    metrics: Dict[str, Any]      # field-level F1
    hall: Dict[str, Any]
    flags: Dict[str, bool]       # nominal_correct / symbol_correct / ...
    is_empty: bool


# ---------------------------------------------------------------------------
# Per-pair evaluation
# ---------------------------------------------------------------------------
def evaluate_pair(pred: Dict[str, Any],
                  gt: Dict[str, Any]) -> Optional[PairResult]:
    """Evaluate one (pred, gt) pair. Returns None if class unknown."""
    region = (pred.get("type") or gt.get("type") or "").strip()
    if region not in NUMERICAL_SCHEMAS:
        return None

    # Pred has nested 'parsed'; GT is flat (with optional _review)
    pred_inner = pred.get("parsed") or {}
    if not pred_inner and "nominal" in pred or "symbol" in pred or "Ra" in pred:
        # Pred file already flat (raw stage3_numerical training data)
        pred_inner = strip_review(pred)
    pred_inner = strip_review(pred_inner)
    gt_inner = strip_review(gt)

    if region == "Measure":
        metrics = compare_measure(pred_inner, gt_inner)
        flags = {
            "nominal_correct":  bool(metrics.get("nominal_correct")),
            "tolerance_correct": bool(metrics.get("tolerance_correct")),
        }
    elif region == "GDT":
        metrics = compare_gdt(pred_inner, gt_inner)
        flags = {
            "symbol_correct": bool(metrics.get("symbol_correct")),
            "datum_correct":  bool(metrics.get("datum_correct")),
        }
    else:  # Roughness
        metrics = compare_roughness(pred_inner, gt_inner)
        flags = {
            "Ra_correct": bool(metrics.get("Ra_correct")),
        }

    allowed = NUMERICAL_SCHEMAS.get(region, set())
    hall = hallucination_rate(pred_inner, gt_inner, allowed_keys=allowed)

    is_empty = not any(
        v not in (None, "", [], {}) for v in pred_inner.values()
    )

    return PairResult(
        image_stem="",
        region_class=region,
        pred_inner=pred_inner,
        gt_inner=gt_inner,
        metrics=metrics,
        hall=hall,
        flags=flags,
        is_empty=is_empty,
    )


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------
def aggregate_overall(pairs: List[PairResult]) -> Dict[str, Any]:
    by_class: Dict[str, List[PairResult]] = defaultdict(list)
    for p in pairs:
        by_class[p.region_class].append(p)

    cls_summaries: Dict[str, Dict[str, Any]] = {}
    total_tp = total_fp = total_fn = 0
    total_hall = 0
    total_pred_fields = 0
    total_empty = 0

    for cls, ps in by_class.items():
        tp = sum(p.metrics.get("tp", 0) for p in ps)
        fp = sum(p.metrics.get("fp", 0) for p in ps)
        fn = sum(p.metrics.get("fn", 0) for p in ps)
        f = pr_f1(tp, fp, fn)

        h_count = sum(p.hall["n_hallucinations"] for p in ps)
        h_total = sum(p.hall["n_pred_fields"]   for p in ps)
        h_rate = round(safe_div(h_count, max(1, h_total)), 4)

        empty = sum(1 for p in ps if p.is_empty)

        cls_summary = {
            "n_pairs": len(ps),
            "f1": f["f1"], "precision": f["precision"], "recall": f["recall"],
            "tp": tp, "fp": fp, "fn": fn,
            "hallucination_rate": h_rate,
            "empty_rate": round(safe_div(empty, len(ps)), 4),
        }

        # Class-specific flag rates
        if cls == "Measure":
            cls_summary["nominal_accuracy"] = round(
                safe_div(sum(1 for p in ps if p.flags["nominal_correct"]),
                         len(ps)), 4)
            cls_summary["tolerance_match"] = round(
                safe_div(sum(1 for p in ps if p.flags["tolerance_correct"]),
                         len(ps)), 4)
        elif cls == "GDT":
            cls_summary["symbol_accuracy"] = round(
                safe_div(sum(1 for p in ps if p.flags["symbol_correct"]),
                         len(ps)), 4)
            cls_summary["datum_accuracy"] = round(
                safe_div(sum(1 for p in ps if p.flags["datum_correct"]),
                         len(ps)), 4)
        elif cls == "Roughness":
            cls_summary["Ra_accuracy"] = round(
                safe_div(sum(1 for p in ps if p.flags["Ra_correct"]),
                         len(ps)), 4)

        cls_summaries[cls] = cls_summary

        total_tp += tp
        total_fp += fp
        total_fn += fn
        total_hall += h_count
        total_pred_fields += h_total
        total_empty += empty

    overall = pr_f1(total_tp, total_fp, total_fn)
    overall["hallucination_rate"] = round(
        safe_div(total_hall, max(1, total_pred_fields)), 4,
    )
    overall["empty_rate"] = round(
        safe_div(total_empty, max(1, len(pairs))), 4,
    )
    overall["n_pairs"] = len(pairs)

    return {"by_class": cls_summaries, "overall": overall}


def gdt_symbol_breakdown(pairs: List[PairResult]) -> Tuple[List[Dict[str, Any]], float]:
    """Per-GDT-symbol hit rate. Returns (rows, rare_symbol_accuracy).

    "Rare" = bottom 50% of symbols by GT frequency.
    """
    by_symbol: Dict[str, Dict[str, int]] = defaultdict(
        lambda: {"total": 0, "hits": 0},
    )
    for p in pairs:
        if p.region_class != "GDT":
            continue
        gt_sym = (p.gt_inner.get("symbol") or "").strip()
        if not gt_sym:
            continue
        by_symbol[gt_sym]["total"] += 1
        if p.flags["symbol_correct"]:
            by_symbol[gt_sym]["hits"] += 1

    rows = []
    for sym, c in sorted(by_symbol.items(), key=lambda x: -x[1]["total"]):
        rows.append({
            "symbol": sym,
            "total_gt": c["total"],
            "hits": c["hits"],
            "hit_rate": round(safe_div(c["hits"], c["total"]), 4),
        })

    if not rows:
        return rows, 0.0

    # Rare = bottom half by frequency
    half = max(1, len(rows) // 2)
    rare_rows = rows[-half:]
    rare_total = sum(r["total_gt"] for r in rare_rows)
    rare_hits  = sum(r["hits"]     for r in rare_rows)
    rare_acc = round(safe_div(rare_hits, max(1, rare_total)), 4)
    return rows, rare_acc


# ---------------------------------------------------------------------------
# Main check
# ---------------------------------------------------------------------------
def run(predictions_dir: Path,
        gt_dir: Path,
        thresholds_path: Path) -> ValidationReport:
    thr = load_thresholds(thresholds_path)

    pred_map = discover_predictions(predictions_dir)
    gt_map   = discover_gt(gt_dir)

    report = ValidationReport(
        title="V6 — Stage 3-N (Donut Numerical fine-tuned) Validation ★ D-023",
        step="stage3n",
        metadata={
            "predictions_dir": str(predictions_dir),
            "gt_dir": str(gt_dir),
            "n_pred": len(pred_map),
            "n_gt": len(gt_map),
        },
    )

    if not pred_map or not gt_map:
        report.add_eval(
            "data_loaded", value=0, threshold=1, direction="ge",
            severity=Severity.CRITICAL,
            message=f"pred={len(pred_map)} gt={len(gt_map)}",
        )
        return report

    # ---- Per-pair eval ----------------------------------------------
    pairs: List[PairResult] = []
    skipped_incomplete = 0
    parse_errors: List[str] = []
    unmatched: List[str] = []

    for stem, ppath in pred_map.items():
        if stem not in gt_map:
            unmatched.append(stem)
            continue
        pred = load_json_safe(ppath)
        gt   = load_json_safe(gt_map[stem])
        if pred is None or gt is None:
            parse_errors.append(stem)
            continue
        if not gt_is_completed(gt):
            skipped_incomplete += 1
            continue

        result = evaluate_pair(pred, gt)
        if result is None:
            parse_errors.append(f"{stem} (unknown class)")
            continue
        result.image_stem = stem
        pairs.append(result)

    log.info("Evaluated %d pairs (unmatched=%d incomplete=%d errors=%d)",
             len(pairs), len(unmatched), skipped_incomplete, len(parse_errors))

    if not pairs:
        report.add_eval(
            "pairs_evaluated", value=0, threshold=1, direction="ge",
            severity=Severity.CRITICAL,
            message=("No matching (pred, completed-gt) pairs. "
                     "Check that GT JSONs have _review.completed=true "
                     "or no _review block."),
        )
        return report

    agg = aggregate_overall(pairs)
    by_class = agg["by_class"]
    overall = agg["overall"]

    # ---- ★ Per-class F1 (D-023) -------------------------------------
    try:
        ff_node = threshold_lookup(thr, "stage3n.field_f1_min")
    except KeyError:
        ff_node = {}

    for cls in ("Measure", "GDT", "Roughness"):
        if cls not in by_class:
            continue
        spec = ff_node.get(cls, {})
        report.add_eval(
            f"field_f1[{cls}]",
            value=by_class[cls]["f1"],
            threshold=spec.get("threshold",
                               0.90 if cls == "Measure" else
                               0.95 if cls == "GDT" else 0.95),
            direction="ge",
            severity=spec.get("severity",
                              "critical" if cls in ("Measure", "GDT") else "warning"),
            message=f"n={by_class[cls]['n_pairs']} | "
                    f"논문 {'0.923' if cls == 'Measure' else '0.965' if cls == 'GDT' else '1.0'}",
        )

    report.add_eval(
        "field_f1[overall]", value=overall["f1"],
        threshold=None, direction="none", severity=Severity.INFO,
        message=f"n={overall['n_pairs']} | 논문 0.963",
    )

    # ---- ★ Numerical accuracy (Measure nominal) ---------------------
    measure = by_class.get("Measure", {})
    if measure:
        try:
            n_node = threshold_lookup(thr, "stage3n.numerical_accuracy_min")
            n_thr, n_sev = n_node["threshold"], n_node.get("severity", "critical")
        except KeyError:
            n_thr, n_sev = 0.95, "critical"
        report.add_eval(
            "numerical_accuracy (★)",
            value=measure["nominal_accuracy"],
            threshold=n_thr, direction="ge", severity=n_sev,
            message="Measure nominal 값이 GT 와 ±0.01 mm 이내 매칭 비율",
        )

        try:
            t_node = threshold_lookup(thr, "stage3n.tolerance_match_min")
            t_thr, t_sev = t_node["threshold"], t_node.get("severity", "critical")
        except KeyError:
            t_thr, t_sev = 0.90, "critical"
        report.add_eval(
            "tolerance_match (★)",
            value=measure["tolerance_match"],
            threshold=t_thr, direction="ge", severity=t_sev,
            message="upper + lower 모두 정확히 매칭",
        )

    # ---- GDT symbol & datum accuracy --------------------------------
    gdt = by_class.get("GDT", {})
    if gdt:
        report.add_eval(
            "symbol_accuracy[GDT]", value=gdt["symbol_accuracy"],
            threshold=0.95, direction="ge", severity=Severity.WARNING,
            message="ISO 1101 14개 심볼 Unicode exact match",
        )
        report.add_eval(
            "datum_accuracy[GDT]", value=gdt["datum_accuracy"],
            threshold=0.90, direction="ge", severity=Severity.WARNING,
            message="datum list (순서 일치)",
        )

        # Per-symbol breakdown + rare symbol accuracy
        sym_rows, rare_acc = gdt_symbol_breakdown(pairs)
        try:
            r_node = threshold_lookup(thr, "stage3n.rare_symbol_accuracy_min")
            r_thr, r_sev = r_node["threshold"], r_node.get("severity", "warning")
        except KeyError:
            r_thr, r_sev = 0.70, "warning"
        report.add_eval(
            "rare_symbol_accuracy", value=rare_acc,
            threshold=r_thr, direction="ge", severity=r_sev,
            message="GT 빈도 하위 50% 심볼만 별도 측정",
        )
        if sym_rows:
            report.add_table(
                "Per-symbol hit rate (GDT)",
                rows=sym_rows,
                columns=["symbol", "total_gt", "hits", "hit_rate"],
                description="ISO 1101 심볼별 정확도. 빈도 내림차순.",
            )
            report.add_plot(
                "Per-symbol hit rate (GDT)",
                make_bar_chart(
                    labels=[r["symbol"] for r in sym_rows],
                    values=[r["hit_rate"] for r in sym_rows],
                    title="Symbol accuracy",
                    ylabel="hit rate", ylim=(0.0, 1.0),
                ),
            )

    # ---- Roughness Ra accuracy --------------------------------------
    rough = by_class.get("Roughness", {})
    if rough:
        report.add_eval(
            "Ra_accuracy[Roughness]", value=rough["Ra_accuracy"],
            threshold=0.90, direction="ge", severity=Severity.WARNING,
            message="Ra value 매칭 (±0.05 μm)",
        )

    # ---- ★ Hallucination --------------------------------------------
    try:
        h_node = threshold_lookup(thr, "stage3n.hallucination_rate_max")
        h_thr, h_sev = h_node["threshold"], h_node.get("severity", "critical")
    except KeyError:
        h_thr, h_sev = 0.10, "critical"
    report.add_eval(
        "hallucination_rate (overall, ★)",
        value=overall["hallucination_rate"],
        threshold=h_thr, direction="le", severity=h_sev,
        message="논문 overall 0.067",
    )
    for cls, cs in by_class.items():
        report.add_eval(
            f"hallucination_rate[{cls}]",
            value=cs["hallucination_rate"],
            threshold=None, direction="none", severity=Severity.INFO,
        )

    # ---- Empty response ---------------------------------------------
    report.add_eval(
        "empty_rate (overall)", value=overall["empty_rate"],
        threshold=0.05, direction="le", severity=Severity.WARNING,
        message="parsed 가 비어있는 비율",
    )

    # ---- Per-class summary table ------------------------------------
    summary_rows = []
    for cls, cs in by_class.items():
        row = {
            "class": cls, "n": cs["n_pairs"],
            "f1": cs["f1"], "precision": cs["precision"], "recall": cs["recall"],
            "hall": cs["hallucination_rate"],
            "empty": cs["empty_rate"],
        }
        # Class-specific
        if cls == "Measure":
            row["nominal_acc"] = cs.get("nominal_accuracy")
            row["tol_match"]   = cs.get("tolerance_match")
        elif cls == "GDT":
            row["sym_acc"]   = cs.get("symbol_accuracy")
            row["datum_acc"] = cs.get("datum_accuracy")
        elif cls == "Roughness":
            row["Ra_acc"] = cs.get("Ra_accuracy")
        summary_rows.append(row)

    report.add_table(
        "Per-class summary",
        rows=summary_rows,
        columns=["class", "n", "f1", "precision", "recall",
                 "hall", "empty",
                 "nominal_acc", "tol_match",
                 "sym_acc", "datum_acc", "Ra_acc"],
    )

    # ---- F1 per class chart -----------------------------------------
    if by_class:
        report.add_plot(
            "F1 per class",
            make_bar_chart(
                labels=list(by_class.keys()),
                values=[v["f1"] for v in by_class.values()],
                title="Stage 3-N F1 by class",
                ylabel="F1", ylim=(0.0, 1.0),
            ),
        )

    # ---- Unmatched / errors -----------------------------------------
    if unmatched:
        report.add_eval(
            "unmatched_predictions", value=len(unmatched),
            threshold=0, direction="le", severity=Severity.INFO,
            message="GT 없는 예측 (test split 외 케이스 가능)",
        )
    if skipped_incomplete:
        report.add_eval(
            "skipped_incomplete_gt", value=skipped_incomplete,
            threshold=0, direction="le", severity=Severity.INFO,
            message="GT 의 _review.completed=false → 평가에서 제외",
        )
    if parse_errors:
        report.add_eval(
            "parse_errors", value=len(parse_errors),
            threshold=0, direction="le", severity=Severity.WARNING,
        )

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="V6 — Stage 3-N (Donut Numerical fine-tuned) validation. "
                    "★ D-023 사용자 필수 임계값 측정.",
    )
    p.add_argument("--predictions", type=Path, required=True,
                   help="Stage 3-N 출력 폴더 (*.num.json)")
    p.add_argument("--gt", type=Path, required=True,
                   help="Ground truth 폴더 (data/vlm/numerical/ 사람 검수 후)")
    p.add_argument("--thresholds", type=Path, default=DEFAULT_THRESHOLDS_PATH)
    p.add_argument("--reports-dir", type=Path, default=DEFAULT_REPORTS_DIR)
    p.add_argument("--no-color", action="store_true")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    log.info("Predictions : %s", args.predictions)
    log.info("Ground truth: %s", args.gt)

    if not args.predictions.exists():
        log.error("predictions dir not found: %s", args.predictions)
        return 2
    if not args.gt.exists():
        log.error("gt dir not found: %s", args.gt)
        return 2

    report = run(args.predictions, args.gt, args.thresholds)
    paths = report.emit(reports_dir=args.reports_dir,
                        use_color=not args.no_color)
    log.info("HTML : %s", paths["html"])
    log.info("JSON : %s", paths["json"])
    return 0 if report.overall_status in (Status.PASS, Status.WARN, Status.INFO) else 1


if __name__ == "__main__":
    sys.exit(main())
